### ISSUE TITLE
v1.10.0 broke built-in adapter factories (awssdks3v3 in my case)

### ISSUE THREAD

**Issue by eXtreme** [1up-lab/OneupFlysystemBundle#132]
So after upgrading my dependencies from FlysystemBundle 1.9.0 to 1.10.0 my flysystem config is broken. I use AWSS3v3 adapter and I got this:

```
PHP Fatal error:  Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "awss3v3" under "oneup_flysystem.adapters.article_media_adapter" in /srv/(...)/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:317
Stack trace:
#0 /srv/(...)/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(264): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#1 /srv/(...)/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php(283): Symfony\Component\Config\Definition\BaseNode->normalize(Array)
#2 /srv/(...)/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(264): Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue(Array)
#3 /srv/(...)/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php(307): Symfony\Component\Config\Def in /srv/(...)/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 317
```

This is clearly problem with 1.10.0 because downgrading just flysystem bundle to 1.9.0 "fixes" the problem. 

My guess is that #127 broke something there.

**Comment by bytehead** [comment]
Yes, it's already fixed in [1.10.1](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/1.10.1). See #129 and #130 for more information.

**Comment by eXtreme** [comment]
@bytehead jesus that was fast :) when I started writting this issue there was no 1.10.1 ;)

**Comment by bytehead** [comment]
@chosroes was fast with his PR!
